apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-v2
  labels:
    app: nginx
    env: UAT
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80  #port for internal 
