name: Deploy to Kind Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      KUBECONFIG: C:\kube\config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify cluster
        run: kubectl get nodes

      - name: Deploy Kubernetes manifests
        run: kubectl apply -f k8s/
